apiVersion: infra.management.ibm.com/v1alpha1
kind: Connection
metadata:
  labels:
  name: conn1  
spec:
  cfHost: manageiq.mcmpoc.com
  secrets:
    accessToken:
      secretKeyRef:
        key: accesstoken
        name: conn1secret